"""Process-lifetime API resources (dev doc §11.2), module M10b.

Loaded once at server startup, reused by every episode created —
the real Kurla dependency graph, flood-susceptibility raster, road
network, ward polygon, policy registry, and risk/router calibrations
(same "load once, reuse per episode" convention `envs/single_env.py`/
`multi_env.py` already established for the raster/road network
specifically).

**Disclosed:** the router/risk calibration files (`configs/router_
calibration.json`/`configs/risk_calibration.json`) are optional —
built once by `scripts/calibrate_router.py`/`scripts/calibrate_risk.py`
(M8/M9b), not regenerated by the API itself. Missing files fall back to
an all-zero calibration (routes everything OOD / reads risk as always
0 — the same disclosed-neutral-default convention `risk/engine.py`'s
own `normalize_to_p95` already uses for a zero reference), logged as a
warning, not a startup failure — the server should still come up and
be useful for basic twin/episode stepping even without either
calibration file present.
"""

from __future__ import annotations

import json
from typing import Any

import structlog
from shapely.geometry import shape
from shapely.geometry.base import BaseGeometry

from udt.agents.marl.registry import load_registry
from udt.common.config import REPO_ROOT, get_settings
from udt.common.models import (
    DependencyGraph,
    PolicyRegistryEntry,
    RiskCalibration,
    RouterCalibration,
)
from udt.common.versions import ENV_VERSION
from udt.incidents.degradations.flood import SusceptibilityRaster
from udt.twin.road_network import RoadNetwork

log = structlog.get_logger()


_ZERO_RISK_CALIBRATION = RiskCalibration(
    p95_risk_raw=0.0, p95_disagreement_raw=0.0, conformal_threshold=0.0, p95_interval_width=0.0
)


class AppContext:
    def __init__(self) -> None:
        self.env_version = ENV_VERSION
        settings = get_settings()
        processed_dir = settings.data_dir / "processed"

        with (processed_dir / "dependency_graph.json").open() as f:
            self.dep_graph = DependencyGraph.model_validate(json.load(f))
        with (processed_dir / "ward_boundary.geojson").open() as f:
            self.ward_boundary: dict[str, Any] = json.load(f)
        self.ward_polygon: BaseGeometry = shape(self.ward_boundary["features"][0]["geometry"])

        self.raster = SusceptibilityRaster(processed_dir / "flood_susceptibility.tif")
        roads_full_path = processed_dir / "roads_full.graphml"
        self.road_network: RoadNetwork | None = (
            RoadNetwork.load(roads_full_path, self.raster) if roads_full_path.exists() else None
        )
        if self.road_network is None:
            log.warning("api_road_network_not_found", expected_path=str(roads_full_path))

        self.registry_entries: list[PolicyRegistryEntry] = load_registry(
            REPO_ROOT / "registry" / "policies.yaml"
        )

        router_calibration_path = REPO_ROOT / "configs" / "router_calibration.json"
        self.router_calibration: RouterCalibration | None = None
        if router_calibration_path.exists():
            self.router_calibration = RouterCalibration.model_validate_json(
                router_calibration_path.read_text()
            )
        else:
            log.warning(
                "api_no_router_calibration_found",
                hint="run scripts/calibrate_router.py - every episode will route OOD until then",
                path=str(router_calibration_path),
            )

        risk_calibration_path = REPO_ROOT / "configs" / "risk_calibration.json"
        self.risk_calibration: RiskCalibration = _ZERO_RISK_CALIBRATION
        if risk_calibration_path.exists():
            self.risk_calibration = RiskCalibration.model_validate_json(
                risk_calibration_path.read_text()
            )
        else:
            log.warning(
                "api_no_risk_calibration_found",
                hint="run scripts/calibrate_risk.py - risk will always normalize to 0.0 until then",
                path=str(risk_calibration_path),
            )

    def close(self) -> None:
        self.raster.close()
